POST http://localhost:1337/v1/chat/completions
Content-Type: application/json

{
  "messages": [
    {
      "content": "You are a helpful assistant.",
      "role": "system"
    },
    {
      "content": "오늘 저녁 뭐 먹지?",
      "role": "user"
    }
  ],
  "model": "solar-10.7b-slerp",
  "stream": false,
  "max_tokens": 2048,
  "stop": [
    "hello"
  ],
  "frequency_penalty": 0,
  "presence_penalty": 0,
  "temperature": 0.7,
  "top_p": 0.95
}