apiVersion: v1	
kind: PersistentVolume	
metadata:
  name: pv-01	
spec:	
  accessModes:	
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  persistentVolumeReclaimPolicy: Retain	
  storageClassName: pv-test-01	
  nfs:
    server: 10.0.2.6	
    path: /tmp/k8s-pv
