PIP=../../venv/bin/pip
PYTHON=../../venv/bin/python

init:
	$(PIP) install -r requirements.lock

node2vec:
	PYTHONPATH=../../ $(PYTHON) "listings/13.1 Applying node2vec embeddings to Karate Club’s Network.py"

gnn:
	PYTHONPATH=../../ $(PYTHON) listings/GNN_all_in_one.py