apiVersion: v1	
kind: Service
metadata:	
  name: sfs-service01	
spec:	
  selector:	
    app.kubernetes.io/name: web-sfs01	
  type: ClusterIP
  clusterIP: None	
  ports:	
  - protocol: TCP	
    port: 80
