version: "3"

services:
  flasktest:
    build: ./myFlask_ws
    networks:
      - composenet03
    volumes:
      - ./myFlask_ws:/usr/src/app
      - ./pages:/usr/src/app/pages
    restart: always

  nginxtest:
    build: ./myNginx_wsf
    networks:
      - composenet03
    ports:
      - "81:81"
    volumes:
      - ./myNginx_wsf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flasktest
    restart: always

networks:
  composenet03: