apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-test01	
spec:	
  replicas: 5	
  selector:	
    matchLabels:	
      app.kubernetes.io/name: web-deploy
  template:	
    metadata:	
      labels:	
        app.kubernetes.io/name: web-deploy
    spec:
      containers:
      - name: nginx	
        image: nginx:latest
