version: '3'
services:
  jupyterlab:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - /d/drive/SelfStudy/ds4th_study:/workspace/ds4th # ds4th_study가 설치되어 있는 경로로 변경
    environment:
      - JUPYTER_ENABLE_LAB=yes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]