# mysql-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQxMjM=  # password123 in base64
  MYSQL_PASSWORD: cGFzc3dvcmQxMjM=       # password123 in base64