apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sfs-test01
spec:		
  replicas: 3		
  selector:				
    matchLabels:			
      app.kubernetes.io/name: web-sfs01				
  serviceName: sfs-service01		
  template:			
    metadata:			
      labels:			
        app.kubernetes.io/name: web-sfs01		
    spec:			
      containers:		
      - name: nginx		
        image: nginx:latest
