apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sfs-test01
spec:
  replicas: 1	
  selector:
    matchLabels:
      app.kubernetes.io/name: web-sfs01	
  serviceName: sfs-service01	
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-sfs01		
    spec:
      containers:	
      - name: nginx
        image: nginx:latest
        volumeMounts:		
        - name: sfs-vol01
          mountPath: /mount01
  volumeClaimTemplates:			
  - metadata:	
      name: sfs-vol01		
    spec:			
      accessModes: [ "ReadWriteOnce" ]		
      storageClassName: pv-sfs-test01
      resources:	
        requests:		
          storage: 20Mi		

