apiVersion: v1
kind: Service	
metadata:
  name: django-service
spec:
  selector:
    app.kubernetes.io/name: web-deploy
  type: ClusterIP	
  ports:
  - protocol: TCP	
    port: 80	
    targetPort: 80
